server:
  port: "8080"
  debug: true


redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  pass:

database:
  name: example_db
  host: "127.0.0.1"
  port: 3306
  user: root
  pass:


log:
  development: true        # 是否开启开发模式 true: 开启 false: 关闭
  disableStacktrace: false # 是否禁用堆栈跟踪
  encoding: "json"         # 编码格式 json: json格式 console: 控制台格式
  level: "info"            # 日志级别 debug: 调试 info: 信息 warn: 警告 error: 错误 dpanic: 严重 panic: 恐慌 fatal: 致命
  name: "example"          # 日志名称
  writers: "all"  # 日志输出方式 console: 控制台 file: 文件
  loggerDir: "./logs"      # 日志目录
  logMaxSize: 128           # 单个日志文件最大大小 单位: MB
  logMaxAge: 365             # 日志保留天数
  logCompress: false       # 是否压缩日志文件